### ISSUE TITLE
Remove !important  from this statement !!

### ISSUE THREAD

**Issue by Iulian33** [rickolynch/date-range-picker#1]
https://github.com/rickolynch/date-picker-directive/blob/300c4d3a2a4b18df1ea68726fa621f81b09e20fc/src/app/modules/datepicker/daterangepicker/daterangepicker.component.scss#L120

I can not overwrite styles because of importants you put here  , I can not change color

**Comment by rickolynch** [comment]
Thanks for the feedback. The issue is now resolved. Please update to version 1.0.16.

**Comment by rickolynch** [comment]
switch to https://github.com/rickolynch/daterangepicker or do npm i date-picker-directive

**Comment by Iulian33** [comment]
Thanks , now is perfect !
